name: Repository Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  container:
    runs-on: ubuntu-latest
    container: opentosca/winery-cli:latest
    steps:
      - uses: actions/checkout@v3
      - run: winery-cli -cd --path $GITHUB_WORKSPACE
